version: "2"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./web/source/:/var/www/html/:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log/:/var/log/nginx/:rw
    links:
      - web

  web:
    build: ./web/
    image: flask_web
    expose:
      - "5000"
    volumes:
      - ./web/source/:/var/www/html/:rw
    depends_on:
      - db
    command: python manage.py runserver --host 0.0.0.0


  db:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/:rw
    environment:
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
